# Generated by Django 5.0.4 on 2024-06-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_topic_room_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='subject',
        ),
    ]
