# Generated by Django 5.0.4 on 2024-06-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_room_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.subject'),
        ),
    ]
